export interface Product {
  id: string;
  nombre: string;
  descripcion: string;
  precio: number;
  icon: string;
  categoria: string;
  badge?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "giftcard-amazon-500",
    nombre: "Gift Card Amazon",
    descripcion: "Saldo para Amazon México",
    precio: 500,
    icon: "🎁",
    categoria: "Gift Cards",
    badge: "Popular",
  },
  {
    id: "giftcard-amazon-1000",
    nombre: "Gift Card Amazon",
    descripcion: "Saldo para Amazon México",
    precio: 1000,
    icon: "🎁",
    categoria: "Gift Cards",
  },
  {
    id: "giftcard-mercadolibre-500",
    nombre: "Gift Card Mercado Libre",
    descripcion: "Saldo para Mercado Libre",
    precio: 500,
    icon: "🛒",
    categoria: "Gift Cards",
  },
  {
    id: "giftcard-mercadolibre-1000",
    nombre: "Gift Card Mercado Libre",
    descripcion: "Saldo para Mercado Libre",
    precio: 1000,
    icon: "🛒",
    categoria: "Gift Cards",
  },
  {
    id: "giftcard-shein-500",
    nombre: "Gift Card Shein",
    descripcion: "Saldo para Shein México",
    precio: 500,
    icon: "👗",
    categoria: "Gift Cards",
  },
  {
    id: "giftcard-liverpool-500",
    nombre: "Gift Card Liverpool",
    descripcion: "Saldo para Liverpool",
    precio: 500,
    icon: "🏬",
    categoria: "Gift Cards",
  },
  {
    id: "usdt-50",
    nombre: "USDT Pack 50",
    descripcion: "50 USDT a tu wallet externa",
    precio: 950,
    icon: "💎",
    categoria: "USDT Packs",
    badge: "Entrada",
  },
  {
    id: "usdt-100",
    nombre: "USDT Pack 100",
    descripcion: "100 USDT a tu wallet externa",
    precio: 1900,
    icon: "💎",
    categoria: "USDT Packs",
  },
  {
    id: "usdt-250",
    nombre: "USDT Pack 250",
    descripcion: "250 USDT a tu wallet externa",
    precio: 4750,
    icon: "💎",
    categoria: "USDT Packs",
  },
  {
    id: "usdt-500",
    nombre: "USDT Pack 500",
    descripcion: "500 USDT a tu wallet externa",
    precio: 9500,
    icon: "💎",
    categoria: "USDT Packs",
    badge: "Recomendado",
  },
  {
    id: "usdt-1000",
    nombre: "USDT Pack 1000",
    descripcion: "1000 USDT a tu wallet externa",
    precio: 19000,
    icon: "💎",
    categoria: "USDT Packs",
    badge: "Premium",
  },
  {
    id: "vpn-mensual",
    nombre: "VPN Seguro",
    descripcion: "VPN cifrado por 1 mes",
    precio: 149,
    icon: "🔒",
    categoria: "Digitales",
  },
  {
    id: "vpn-anual",
    nombre: "VPN Seguro Anual",
    descripcion: "VPN cifrado por 12 meses",
    precio: 999,
    icon: "🔒",
    categoria: "Digitales",
    badge: "Ahorro",
  },
  {
    id: "ebook-seguridad",
    nombre: "E-book: Seguridad Digital",
    descripcion: "Guía completa de seguridad en línea",
    precio: 199,
    icon: "📚",
    categoria: "Digitales",
  },
  {
    id: "curso-defi",
    nombre: "Curso DeFi Básico",
    descripcion: "Introducción a finanzas descentralizadas",
    precio: 499,
    icon: "🎓",
    categoria: "Digitales",
  },
  {
    id: "software-vault",
    nombre: "CT Vault Pro",
    descripcion: "Software de gestión de wallets",
    precio: 1299,
    icon: "💻",
    categoria: "Digitales",
  },
  {
    id: "hoodie-ct",
    nombre: "Hoodie Control Total",
    descripcion: "Hoodie edición limitada",
    precio: 749,
    icon: "🧥",
    categoria: "Físicos",
    badge: "Nuevo",
  },
  {
    id: "tote-ct",
    nombre: "Tote Bag Control Total",
    descripcion: "Bolsa ecológica con diseño exclusivo",
    precio: 299,
    icon: "👜",
    categoria: "Físicos",
  },
  {
    id: "stickers-pack",
    nombre: "Pack Stickers CT",
    descripcion: "5 stickers exclusivos del club",
    precio: 199,
    icon: "🏷️",
    categoria: "Físicos",
  },
  {
    id: "card-fisica",
    nombre: "Tarjeta Física CT",
    descripcion: "Tarjeta metálica personalizada",
    precio: 899,
    icon: "💳",
    categoria: "Físicos",
    badge: "Premium",
  },
];

export const CATEGORIAS = [
  "Todos",
  ...new Set(PRODUCTS.map((p) => p.categoria)),
];
