export const STORES = [
  {
    id: "mercadolibre",
    nombre: "Mercado Libre",
    descripcion: "Compras en línea",
    color: "#FFE600",
    textColor: "#333333",
    icon: "🛒",
    url: "https://www.mercadolibre.com.mx",
    categoria: "Compras",
  },
  {
    id: "paypal",
    nombre: "PayPal",
    descripcion: "Pagos digitales",
    color: "#003087",
    textColor: "#FFFFFF",
    icon: "💳",
    url: "https://www.paypal.com",
    categoria: "Pagos",
  },
  {
    id: "amazon",
    nombre: "Amazon",
    descripcion: "Tienda global",
    color: "#FF9900",
    textColor: "#232F3E",
    icon: "📦",
    url: "https://www.amazon.com.mx",
    categoria: "Compras",
  },
  {
    id: "shein",
    nombre: "Shein",
    descripcion: "Moda y accesorios",
    color: "#222222",
    textColor: "#FFFFFF",
    icon: "👗",
    url: "https://www.shein.com.mx",
    categoria: "Moda",
  },
  {
    id: "liverpool",
    nombre: "Liverpool",
    descripcion: "Departamental",
    color: "#E91E8C",
    textColor: "#FFFFFF",
    icon: "🏬",
    url: "https://www.liverpool.com.mx",
    categoria: "Compras",
  },
  {
    id: "uber",
    nombre: "Uber",
    descripcion: "Transporte y comida",
    color: "#000000",
    textColor: "#FFFFFF",
    icon: "🚗",
    url: "https://www.uber.com",
    categoria: "Servicios",
  },
];
